name: plugin-ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  ci:
    uses: SignalK/signalk-server/.github/workflows/plugin-ci.yml@master
    with:
      node-versions: '["22", "24"]'
